### ISSUE TITLE
The terraform-provider-azurerm_v3.16.0_x5 plugin crashed

### ISSUE THREAD

**Issue by techmonte** [Azure/Mission-Critical-Online#549]
When attempting to run the E2E deployment pipeline, it errors when attempting apply the Terraform configuration in the "Deploy Terraform Global Resources" stage.  An error is thrown: "Plugin did not respond" with additional runtime error exceptions from the Terraform plugin.  Is there a workaround for this?

Stack track and additional error info cited below:

Stack trace from the terraform-provider-azurerm_v3.16.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b2b19e]

```
goroutine 1689 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/frontdoor.resourceFrontDoorUpdate(0x0?, {0x572b400?, 0xc00159ee00})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/frontdoor/frontdoor_resource.go:156 +0x49e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x68303a8?, {0x68303a8?, 0xc001cd0b10?}, 0xd?, {0x572b400?, 0xc00159ee00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000dd9260, {0x68303a8, 0xc001cd0b10}, 0xc000de52b0, 0xc0025c0d00, {0x572b400, 0xc00159ee00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003e3c50, {0x68303a8?, 0xc001cd0a50?}, 0xc0003b5e00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000b550e0, {0x68303a8?, 0xc001cd04b0?}, 0xc00257d030)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5cecee0?, 0xc000b550e0}, {0x68303a8, 0xc001cd04b0}, 0xc001dff2c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000caa80, {0x6841c08, 0xc001141a00}, 0xc001ac5320, 0xc00112d0e0, 0xa87c780, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0000caa80, {0x6841c08, 0xc001141a00}, 0xc001ac5320, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x28a
```

```
Error: The terraform-provider-azurerm_v3.16.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue
```

**Comment by heoelri** [comment]
Hi @techmonte, thanks for raising this issue. We haven't seen this behavior before. Do you've a few more details about the issue? Maybe also a run with `TF_LOG=DEBUG` set?

**Comment by heoelri** [comment]
As this is already a month old and we haven't heard anything back I'll close this issue now.
